### ISSUE TITLE
April 2018 "Startup Talk" meeting agenda

### ISSUE THREAD

**Issue by danawoodman** [startupsonoma/community#2]
# Date

# Location

# Agenda

# Talk

 - [ ] Find Speaker
 - [ ] Directory for Presentations
 
 Instructions to send
 
 ```
 ```
 
 # Announcement
 
 - [ ] Meetup
 - [ ] Facebook
 - [ ] Slack

**Comment by rtyler** [comment]
For potential venues, perhaps we should reach out to one of the companies we had previously discussed as potential partners?

**Comment by rtyler** [comment]
For @danawoodman and @abhiyerra I started to put together a draft of a meetup on April 12th "[Startup Pitch Spring Training](https://www.meetup.com/Startup-Sonoma/events/249103096/)"

In addition to my own pitch, I think it would be ideal for three or four other attendees to share their ~5 minute pitch and provide constructive feedback to each other.
