### ISSUE TITLE
Temporary logo for GitHub Org

### ISSUE THREAD

**Issue by rtyler** [startupsonoma/community#4]
@danawoodman would you mind making some derivative of the Meetup logo?

Otherwise, might I suggest:

![grapes](https://user-images.githubusercontent.com/26594/37686309-2116813c-2c54-11e8-939b-f50b9351bfc6.png)

**Comment by danawoodman** [comment]
🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

**Comment by rtyler** [comment]
@danawoodman created the image below, which I'll use

![meetup-banner](https://user-images.githubusercontent.com/26594/37880869-e5cb122a-3043-11e8-9d06-9cba5aaabe51.jpg)

**Comment by rtyler** [comment]
GOOD ENOUGH FOR NOW
